name=Olimex16x2
version=0.1.5
author=thirstyice
maintainer=thirstyice - https://github.com/thirstyice
sentence=A library for interfacing with the Olimex SHIELD-LCD16x2
paragraph=This library provides a simple programming interface for the Olimex SHIELD-LCD16x2 lcd + button shield for arduino
category=Display
url=https://github.com/thirstyice/Olimex16x2
architectures=*
